# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'images\config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 416)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet(".QFrame {\n"
"    background: rgb(245, 245, 245);\n"
"    border-radius: 3px;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lab_info = QtWidgets.QLabel(self.mainFrame)
        self.lab_info.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.lab_info.setFont(font)
        self.lab_info.setStyleSheet(".QLabel {\n"
"    border:1px solid #b7eb8f;\n"
"    border-radius:3px;\n"
"    line-height: 140px;\n"
"    padding: 5px;\n"
"    color: #434343;\n"
"    background: #f6ffed;\n"
"}")
        self.lab_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_info.setObjectName("lab_info")
        self.verticalLayout.addWidget(self.lab_info)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.combo_user = QtWidgets.QComboBox(self.mainFrame)
        self.combo_user.setMinimumSize(QtCore.QSize(70, 35))
        self.combo_user.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.combo_user.setFont(font)
        self.combo_user.setStyleSheet(".QComboBox {\n"
"    border:1px solid #d9d9d9;\n"
"    border-radius:3px;\n"
"    line-height: 140px;\n"
"    padding:5px 20px;\n"
"    color: #434343;\n"
"}\n"
".QComboBox::drop-down {\n"
"    width: 20px;\n"
"    border-left: 1px solid #d9d9d9;\n"
"}\n"
".QComboBox::down-arrow {\n"
"    image: url(:/icon/arrow-down.png)\n"
"}")
        self.combo_user.setObjectName("combo_user")
        self.horizontalLayout_2.addWidget(self.combo_user)
        self.btn_file = QtWidgets.QPushButton(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_file.sizePolicy().hasHeightForWidth())
        self.btn_file.setSizePolicy(sizePolicy)
        self.btn_file.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.btn_file.setFont(font)
        self.btn_file.setStyleSheet(".QPushButton {\n"
"    height: 24px;\n"
"    padding: 0px 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 3px;\n"
"    color: rgba(0,0,0,.65);\n"
"    background-color: #fff;\n"
"    border: 1px solid #d9d9d9;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    height: 24px;\n"
"    padding: 0px 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 3px;\n"
"    color: #40a9ff;\n"
"    background-color: #fff;\n"
"    border: 1px solid #40a9ff;\n"
"}\n"
"")
        self.btn_file.setObjectName("btn_file")
        self.horizontalLayout_2.addWidget(self.btn_file)
        self.btn_close = QtWidgets.QPushButton(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        self.btn_close.setFont(font)
        self.btn_close.setStyleSheet(".QPushButton {\n"
"    height: 24px;\n"
"    padding: 0px 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 3px;\n"
"    color: rgba(0,0,0,.65);\n"
"    background-color: #fff;\n"
"    border: 1px solid #d9d9d9;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    height: 24px;\n"
"    padding: 0px 10px;\n"
"    font-size: 14px;\n"
"    border-radius: 3px;\n"
"    color: #40a9ff;\n"
"    background-color: #fff;\n"
"    border: 1px solid #40a9ff;\n"
"}\n"
"")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.check_is_clean = QtWidgets.QCheckBox(self.mainFrame)
        self.check_is_clean.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.check_is_clean.setFont(font)
        self.check_is_clean.setStyleSheet("QCheckBox::indicator::unchecked {   \n"
"    image: url(:/icon/复选.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator::checked { \n"
"    image: url(:/icon/复选1.svg);\n"
"}")
        self.check_is_clean.setObjectName("check_is_clean")
        self.horizontalLayout_8.addWidget(self.check_is_clean)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_100 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_100.setObjectName("horizontalLayout_100")
        spacerItem5 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_100.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_100.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_100)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.check_picdown = QtWidgets.QCheckBox(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(False)
        font.setWeight(50)
        self.check_picdown.setFont(font)
        self.check_picdown.setStyleSheet("QCheckBox::indicator::unchecked {   \n"
"    image: url(:/icon/复选.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator::checked { \n"
"    image: url(:/icon/复选1.svg);\n"
"}")
        self.check_picdown.setObjectName("check_picdown")
        self.horizontalLayout_7.addWidget(self.check_picdown)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.check_files = QtWidgets.QCheckBox(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.check_files.setFont(font)
        self.check_files.setStyleSheet("QCheckBox::indicator::unchecked {   \n"
"    image: url(:/icon/复选.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator::checked { \n"
"    image: url(:/icon/复选1.svg);\n"
"}")
        self.check_files.setObjectName("check_files")
        self.horizontalLayout_6.addWidget(self.check_files)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.check_video = QtWidgets.QCheckBox(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.check_video.setFont(font)
        self.check_video.setStyleSheet("QCheckBox::indicator::unchecked {   \n"
"    image: url(:/icon/复选.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator::checked { \n"
"    image: url(:/icon/复选1.svg);\n"
"}")
        self.check_video.setObjectName("check_video")
        self.horizontalLayout_5.addWidget(self.check_video)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.check_picscache = QtWidgets.QCheckBox(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.check_picscache.setFont(font)
        self.check_picscache.setStyleSheet("QCheckBox::indicator::unchecked {   \n"
"    image: url(:/icon/复选.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator::checked { \n"
"    image: url(:/icon/复选1.svg);\n"
"}")
        self.check_picscache.setObjectName("check_picscache")
        self.horizontalLayout_4.addWidget(self.check_picscache)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem14 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.label_21 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.line_gobackdays = QtWidgets.QLineEdit(self.mainFrame)
        self.line_gobackdays.setMinimumSize(QtCore.QSize(70, 35))
        self.line_gobackdays.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.line_gobackdays.setFont(font)
        self.line_gobackdays.setStyleSheet(".QLineEdit {\n"
"    border:1px solid #d9d9d9;\n"
"    border-radius:3px;\n"
"    line-height: 140px;\n"
"    padding: 5px;\n"
"    color: #434343;\n"
"}\n"
"\n"
".QLineEdit:hover {\n"
"    border:1px solid #40a9ff;\n"
"    border-radius:3px;\n"
"    line-height: 140px;\n"
"    padding: 5px;\n"
"    color: #434343;\n"
"}")
        self.line_gobackdays.setText("")
        self.line_gobackdays.setObjectName("line_gobackdays")
        self.horizontalLayout_3.addWidget(self.line_gobackdays)
        self.label_3 = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.label = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setStyleSheet(".QLabel {\n"
"    color: #434343;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.mainFrame, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 1, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Config"))
        self.lab_info.setText(_translate("MainWindow", "一切都准备好！"))
        self.btn_file.setText(_translate("MainWindow", "+自定义路径"))
        self.btn_close.setText(_translate("MainWindow", "保存"))
        self.check_is_clean.setText(_translate("MainWindow", "是否对该账号进行下列内容的清理"))
        self.label_2.setText(_translate("MainWindow", "请勾选你要清理的文件格式："))
        self.check_picdown.setText(_translate("MainWindow", "图片"))
        self.check_files.setText(_translate("MainWindow", "接收的文件（PPT、Doc 等）"))
        self.check_video.setText(_translate("MainWindow", "视频（视频文件和视频的封面图）"))
        self.check_picscache.setText(_translate("MainWindow", "图片缓存（来自小程序、公众号等）"))
        self.label_21.setText(_translate("MainWindow", "需要保留多久以内的文件："))
        self.line_gobackdays.setPlaceholderText(_translate("MainWindow", "天数"))
        self.label_3.setText(_translate("MainWindow", "天"))
        self.label.setText(_translate("MainWindow", "Clean My Wechat V2.2 - 设置页面"))
import resources_rc
