# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'images\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 466)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("* {\n"
"    font: 9pt \"微软雅黑\";\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setMinimumSize(QtCore.QSize(3, 3))
        self.mainFrame.setStyleSheet(".QFrame {\n"
"    background: rgb(245, 245, 245);\n"
"    border-radius: 3px;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lab_info = QtWidgets.QLabel(self.mainFrame)
        self.lab_info.setMinimumSize(QtCore.QSize(0, 40))
        self.lab_info.setStyleSheet(".QLabel {\n"
"    border:1px solid #b7eb8f;\n"
"    border-radius:3px;\n"
"    line-height: 140px;\n"
"    padding: 5px;\n"
"    color: #434343;\n"
"    background: #f6ffed;\n"
"}")
        self.lab_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_info.setObjectName("lab_info")
        self.verticalLayout.addWidget(self.lab_info)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.lab_logo = QtWidgets.QLabel(self.mainFrame)
        self.lab_logo.setMinimumSize(QtCore.QSize(200, 200))
        self.lab_logo.setStyleSheet(".QLabel {\n"
"    image: url(:/icon/wechat.png);\n"
"}")
        self.lab_logo.setText("")
        self.lab_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_logo.setObjectName("lab_logo")
        self.horizontalLayout_7.addWidget(self.lab_logo)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.bar_progress = QtWidgets.QProgressBar(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bar_progress.sizePolicy().hasHeightForWidth())
        self.bar_progress.setSizePolicy(sizePolicy)
        self.bar_progress.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bar_progress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bar_progress.setStyleSheet(".QProgressBar {\n"
"    background: #fff;\n"
"    border:1px solid #d9d9d9;\n"
"    border-radius: 13px;\n"
"    color: black;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #1890ff;\n"
"    border-radius:12px;\n"
"}")
        self.bar_progress.setProperty("value", 0)
        self.bar_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.bar_progress.setTextVisible(True)
        self.bar_progress.setOrientation(QtCore.Qt.Horizontal)
        self.bar_progress.setInvertedAppearance(False)
        self.bar_progress.setObjectName("bar_progress")
        self.horizontalLayout_2.addWidget(self.bar_progress)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.lab_clean = QtWidgets.QLabel(self.mainFrame)
        self.lab_clean.setStyleSheet(".QLabel {\n"
"    color: rgba(0,0,0,.65);\n"
"    background-color: #fff;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-right: 0px; \n"
"    height: 24px;\n"
"    font-size: 14px;\n"
"    padding: 0px 10px;\n"
"}\n"
".QLabel:hover {\n"
"    color: #40a9ff;\n"
"    background-color: #fff;\n"
"    border: 1px solid #40a9ff;\n"
"    height: 24px;\n"
"    font-size: 14px\n"
"}")
        self.lab_clean.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_clean.setObjectName("lab_clean")
        self.horizontalLayout_3.addWidget(self.lab_clean)
        self.lab_config = QtWidgets.QLabel(self.mainFrame)
        self.lab_config.setMinimumSize(QtCore.QSize(0, 35))
        self.lab_config.setStyleSheet(".QLabel {\n"
"    color: rgba(0,0,0,.65);\n"
"    background-color: #fff;\n"
"    border: 1px solid #d9d9d9;\n"
"    border-right: 0px; \n"
"    height: 24px;\n"
"    font-size: 14px;\n"
"    padding: 0px 10px;\n"
"}\n"
".QLabel:hover {\n"
"    color: #40a9ff;\n"
"    background-color: #fff;\n"
"    border: 1px solid #40a9ff;\n"
"    height: 24px;\n"
"    font-size: 14px\n"
"}")
        self.lab_config.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_config.setObjectName("lab_config")
        self.horizontalLayout_3.addWidget(self.lab_config)
        self.lab_close = QtWidgets.QLabel(self.mainFrame)
        self.lab_close.setMinimumSize(QtCore.QSize(0, 30))
        self.lab_close.setStyleSheet(".QLabel {\n"
"    color: rgba(0,0,0,.65);\n"
"    background-color: #fff;\n"
"    border: 1px solid #d9d9d9;\n"
"    height: 24px;\n"
"    font-size: 14px;\n"
"    padding: 0px 10px;\n"
"}\n"
"\n"
".QLabel:hover {\n"
"    color: #40a9ff;\n"
"    background-color: #fff;\n"
"    border: 1px solid #40a9ff;\n"
"    height: 24px;\n"
"    font-size: 14px\n"
"}")
        self.lab_close.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_close.setObjectName("lab_close")
        self.horizontalLayout_3.addWidget(self.lab_close)
        spacerItem11 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.lab_about = QtWidgets.QLabel(self.mainFrame)
        self.lab_about.setStyleSheet(".QLabel {\n"
"    color: #434343;\n"
"}")
        self.lab_about.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_about.setObjectName("lab_about")
        self.verticalLayout.addWidget(self.lab_about)
        self.gridLayout.addWidget(self.mainFrame, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wechat Cleaner"))
        self.lab_info.setText(_translate("MainWindow", "<html><head/><body><p>已经准备好，可以开始了！</p></body></html>"))
        self.lab_clean.setText(_translate("MainWindow", "<html><head/><body><p>开始</p></body></html>"))
        self.lab_config.setText(_translate("MainWindow", "<html><head/><body><p>设置</p></body></html>"))
        self.lab_close.setText(_translate("MainWindow", "<html><head/><body><p>退出</p></body></html>"))
        self.lab_about.setText(_translate("MainWindow", "<a href='https://github.com/blackboxo/CleanMyWechat'>CleanMyWeChat</a> 感谢原作者blackboxo开源<br><a href='https://github.com/lsy9202/CleanMyWechat_Next'>CleanMyWeChat v2.2</a> lsy9202升级版"))
        self.lab_about.setOpenExternalLinks(True)
        self.lab_about.setStyleSheet(".QLabel { color: #434343; }\n" \
                                      ".QLabel a { color: #434343; text-decoration: none; }\n" \
                                      ".QLabel a:hover { color: #1890ff; text-decoration: underline; }")
import resources_rc
